replicaCount: 1

image:
  repository: python-test-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 5000
  targetPort: 5000
  metricsPort: 8000

# Adăugăm adnotări pentru ca Prometheus să știe să "scaneze" pod-ul
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8000"
  prometheus.io/path: "/metrics"
