replicaCount: 1

image:
  repository: python-test-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 80

# Activăm metricile pentru Prometheus
serviceMesh:
  enabled: false

metrics:
  enabled: true
  path: /metrics
  port: 8000
