prometheus-server:
  retention: 1h
  persistentVolume:
    enabled: false
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 128Mi

# Dezactivăm restul suitei care consumă RAM
alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
