prometheus:
  prometheusSpec:
    retention: 1d
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 256Mi
grafana:
  adminPassword: "admin"
  service:
    type: NodePort
    nodePort: 32500
