controller:
  componentName: "jenkins-controller"
  admin:
    username: "admin"
    password: "password123"
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "300m"
      memory: "1Gi"
  # Mărim timpul de așteptare la pornire
  startupProbe:
    failureThreshold: 30
    periodSeconds: 10
  serviceType: NodePort
  nodePort: 32000
